version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: transaction_project
      MYSQL_ROOT_PASSWORD: roottransaction
      MYSQL_USER: transaction_user
      MYSQL_PASSWORD: transaction_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: transaction_user
      DATABASE_PASSWORD: transaction_password
      DATABASE_NAME: transaction_project
    command: npm run start:dev

volumes:
  db_data: